# params.yaml

embedding_size: 64         # Size of embedding vectors
hidden_size: 256           # Size of hidden layers in RNN/GRU/LSTM
encoder_layers: 3          # Number of encoder layers
decoder_layers: 3          # Number of decoder layers
cell_type: LSTM            # RNN, GRU, or LSTM
dropout: 0.3               # Dropout rate (e.g., 0.2 or 0.3)
batch_size: 512            # Batch size for training
learning_rate: 0.0001       # Learning rate for optimizer
epochs: 20                 # Number of training epochs
max_len_native: 35         # Maximum length for native script input
max_len_roman: 40          # Maximum length for romanized output
device: cuda               # 'cuda' or 'cpu'
pad_token: <pad>           # Padding token
sos_token: <sos>           # Start-of-sequence token
eos_token: <eos>           # End-of-sequence token
unk_token: <unk>           # Unknown token